CREATE TABLE refresh_tokens
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    is_used BOOLEAN,
    token   TEXT,
    user_id BIGINT,
    PRIMARY KEY (id)
);

ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_user_id FOREIGN KEY (user_id) REFERENCES users (id);